theme: jekyll-theme-minimal
title: Felix Yustian Setiono
description: Senior Computer Vision Engineer & CV Team Lead, Edge AI & ML Systems Architect. Projects, experience, publications, and CV.
url: https://felixyustian.github.io
plugins:
  - jekyll-seo-tag
  - jekyll-readme-index
exclude:
  - LICENSE
